# Generated by Django 2.2.11 on 2020-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('before', models.CharField(blank=True, max_length=50)),
                ('after', models.CharField(blank=True, max_length=50)),
                ('repo_name', models.CharField(blank=True, max_length=1000)),
                ('html_url', models.URLField(blank=True, max_length=1000)),
                ('hooks_url', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
