# Generated by Django 2.2.11 on 2020-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githublog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
