# Generated by Django 2.2.11 on 2020-04-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0002_auto_20200403_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='githublog',
            name='commit_message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
