# Generated by Django 2.2.11 on 2020-04-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0003_githublog_commit_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_site', models.CharField(max_length=200)),
                ('request_url', models.URLField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('before', models.CharField(blank=True, max_length=50)),
                ('after', models.CharField(blank=True, max_length=50)),
                ('repo_name', models.CharField(blank=True, max_length=1000)),
                ('html_url', models.URLField(blank=True, max_length=1000)),
                ('hooks_url', models.URLField(blank=True, max_length=1000)),
                ('commit_message', models.CharField(blank=True, max_length=1000)),
                ('extra_info', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='GithubLog',
        ),
    ]
